env:
  browser: true
  commonjs: true
  es2021: true
  cypress/globals: true
extends:
  - eslint:recommended
  - plugin:cypress/recommended
  - google
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  max-len: 
    - error
    - code: 140
plugins:
  - cypress
