describe('🇬🇧 💡 Check specific quota order details',function(){
    Cypress.config('baseUrl')

    it('1.New UK quota numbers post 1 Jan 2021 -054xxx Licensed', function () {
        cy.visit('/commodities/0201100021?day=2&month=1&year=2021#import')
        cy.get('.govuk-tabs__panel')
            cy.contains('Non preferential tariff quota')
        cy.get('.table-line')
            cy.contains('054002').click()
        cy.get('.tariff-info')
            .contains('Information on the availability of this quota can be obtained from the Rural Payments Agency.')
        cy.get('.close [href]').click()
    })

    it('2.New UK quota numbers post 1 Jan 2021 -052xxx Non-Licensed', function () {
        cy.visit('/commodities/0201100021?day=2&month=1&year=2021#import')
        cy.get('.govuk-tabs__panel')
        cy.contains('Non preferential tariff quota')
        cy.get('.table-line')
        cy.contains('052201').click()
        cy.get('.tariff-info')
            .contains('Order number 052201')
        cy.get('.close [href]').click()
    })
    it('3.New UK quota numbers post 1 Jan 2021 -058xxx Non-Licensed', function () {
        cy.visit('/commodities/0201100021?day=2&month=1&year=2021#import')
        cy.get('.govuk-tabs__panel')
        cy.contains('Non preferential tariff quota')
        cy.get('.table-line')
        cy.contains('058400').click()
        cy.get('.tariff-info')
            .contains('Order number 058400')
        cy.get('.close [href]').click()
    })
})
