describe('🇬🇧 🇪🇺 💡 | PrivacyNotice.spec | Privacy Notice for UK and XI |', function() {
  it('Privacy - Page content and links', function() {
    cy.visit('/sections');
    cy.get('.govuk-footer__inline-list > li:nth-of-type(1) > .govuk-footer__link').click();
    cy.contains('Privacy notice');
    cy.contains('This notice sets out');
    cy.contains('How we use your data');
    cy.contains('The purposes for which we are processing your personal data are to:');
    cy.contains('collect web analytics to help us to monitor usage of our service for the purposes of improving it');
    cy.get('a[href="https://www.gov.uk/guidance/hmrc-subject-access-request"]').click();
    cy.contains('Make a subject access request to HMRC');
    cy.go('back');
    cy.contains('Complaints');
    cy.contains('International transfers');
    cy.contains('Your rights');
    cy.contains('Data retention');
    cy.contains('Data security');
    cy.contains('Who we share your data with');
    cy.contains('The legal basis of using your data');
    cy.contains('The data we will process');
    cy.get('p:nth-of-type(21) > a').click();
    cy.contains('Make a complaint about HMRC');
    cy.go('back');
    cy.contains('Office of the Data Protection Officer Privacy Notice').click();
    cy.contains('HMRC Office of the Data Protection Officer Privacy Notice');
    cy.go('back');
    cy.contains('advice.dpa@hmrc.gov.uk.');
    cy.contains('casework@ico.org.uk');
  });
});
