name: " 💰 | Duty Calculator Regression Pack |"
on: [workflow_dispatch]
jobs:
  cypress-run:
    name: "💰 Duty Calculator Regression Tests"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        name: "DC tests"
        continue-on-error: true
        with:
          record: true
          quiet: true
          browser: chrome
          headless: true       
          spec: "/DutyCalculator/*spec.js"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}

