name: " 💰 | Duty Calculator Regression Pack |"
on: [workflow_dispatch]
jobs:
  cypress-run:
    name: "💰 Duty Calculator Regression Tests"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v2
      - run: mkdir -p cypress/reports/mochareports
      - uses: cypress-io/github-action@v2
        name: "DC tests"
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true       
          spec: "*/**/DutyCalculator/*spec.js"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          force: true

