name: " 💰 | Duty Calculator Regression Pack |"
on:
  schedule:
  workflow_dispatch:
jobs:
  cypress-run:
    name: "💰 Duty Calculator Regression Tests"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v2
      - run: mkdir -p cypress/reports/mochareports
      - uses: cypress-io/github-action@v2
        name: "All dc tests"
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true       
          spec: "*/**/DutyCalculator/*spec.js"
      - run: npm run posttests
      - run: ls -l
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/mochareports/
      - run: |
          DATE=$(date +%d-%m-%Y)
          mkdir -p 2/$DATE
          cp -r ./cypress/reports/mochareports/*  docs2/$DATE/
          cp ./cypress/reports/mochareports/report.html docs2/$DATE/index.html
          git add docs2 .
      - run: |
           git config --local user.email "tradetarrif+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          force: true

