name: " 💰 | Duty Calculator Regression Pack |"
on: [workflow_dispatch]
jobs:
  cypress-run:
    name: "💰 Duty Calculator Regression Tests"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        name: "DC Tests"
        continue-on-error: true
        with:
          record: true
          quiet: true
          browser: chrome
          headless: true       
          spec: "cypress/integration/DutyCalculator/dcShared/dcSmokeTestCI.spec.js"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}

