name: "💨 Duty Cal smoke test"
on: [workflow_dispatch]
jobs:
  cypress-run:
    environment: trade-tariff
    env:
      CYPRESS_BASE_URL: "https://staging.trade-tariff.service.gov.uk"
      CYPRESS_SPACE: "STAGING"
      CYPRESS_STAGING_BASIC_AUTH: ${{ secrets.CYPRESS_STAGING_BASIC_AUTH }}
      CYPRESS_STAGING_BASIC_PASSWORD: ${{ secrets.CYPRESS_STAGING_BASIC_PASSWORD }}
      CYPRESS_STAGING_BASIC_USERNAME: ${{ secrets.CYPRESS_STAGING_BASIC_USERNAME }}
    name: DC Smoke on Chrome
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TransformCore/trade-tariff-testing
          ref: refs/heads/main
      - uses: cypress-io/github-action@v4
        with:
          quiet: false
          browser: chrome
          headless: true
          spec: "cypress/e2e/DutyCalculator/dcShared/dcSmokeTestCI.cy.js"
