name: "| Production | Regression Pack |"
on:
  schedule:
    - cron: "00 06 * * *"
  workflow_dispatch:
jobs:
  cypress-run:
    environment: trade-tariff
    env:
      CYPRESS_BASE_URL: "https://www.trade-tariff.service.gov.uk"
      CYPRESS_SPACE: 'PRODUCTION'
    name: "🚦 Regression Tests - UK and XI"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date

      - uses: actions/checkout@v2

      - run: mkdir -p cypress/reports/mochareports

      - uses: cypress-io/github-action@v2
        name: cypress
        id: cypress
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true
          spec: "cypress/integration/HOTT-Shared/smokeTestCI.spec.js"

      - run: npm run posttests

      - run: ls -l

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/mochareports/

      - name: Checkout reports repo
        uses: actions/checkout@v2
        with:
          ref: reports
          path: reports_repo

      - name: Copy report into reports repo
        run: |
          cd reports_repo
          DATE=$(date +%d-%m-%Y)
          mkdir -p docs/production/$DATE
          cp -r ../cypress/reports/mochareports/*  docs/production/$DATE/
          cp ../cypress/reports/mochareports/report.html docs/production/$DATE/index.html

      - name: Commit todays report to reports branch
        run: |
          cd reports_repo
          git config --local user.email "tradetarrif+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Production report for $(date +%d-%m-%Y)" -a

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ steps.cypress.outcome == 'failure' }}
        env:
          SLACK_CHANNEL: "tariffs-regression"
          SLACK_USERNAME: "Production Regression"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ":alphabet-yellow-p:"
          SLACK_TITLE: Cypress finished with - ${{ steps.cypress.outcome }}
          SLACK_MESSAGE: https://trade-tariff.github.io/trade-tariff-testing/production/${{ steps.date.outputs.date }}/
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reports
          directory: reports_repo

      - uses: cypress-io/github-action@v2
        name: " Cypress Dashboard "
        continue-on-error: true
        with:
          record: true
          spec: "*/*/*/cypressDashTest.spec.js"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
