name: "| Staging | Regression Pack |"

on:
  schedule:
    - cron: "45 06 * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    environment: trade-tariff
    env:
      CYPRESS_BASE_URL: "https://staging.trade-tariff.service.gov.uk"
      CYPRESS_SPACE: "STAGING"
      CYPRESS_STAGING_BASIC_AUTH: ${{ secrets.CYPRESS_STAGING_BASIC_AUTH }}
      CYPRESS_STAGING_BASIC_PASSWORD: ${{ secrets.CYPRESS_STAGING_BASIC_PASSWORD }}
      CYPRESS_STAGING_BASIC_USERNAME: ${{ secrets.CYPRESS_STAGING_BASIC_USERNAME }}
    name: " 🛎️ Regression Tests - UK and XI - Staging "
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        name: cypress
        id: cypress
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true
          spec: "cypress/e2e/HOTT-Shared/smokeTestCI.spec.js"
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/mochawesome/
      - name: Checkout reports repo
        uses: actions/checkout@v2
        with:
          ref: reports
          path: reports_repo
      - name: Upload today's report to s3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)

          aws s3 cp --recursive cypress/reports/mochawesome s3://$S3_BUCKET_NAME/trade-tariff-testing/staging/$YEAR/$MONTH/$DAY/
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "tariffs-regression"
          SLACK_USERNAME: "Staging Regression"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":alphabet-yellow-s:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Cypress finished with - ${{ steps.cypress.outcome }}
          SLACK_MESSAGE: https://trade-tariff.github.io/trade-tariff-testing/staging/${{ steps.date.outputs.date }}/
      - uses: cypress-io/github-action@v2
        name: " Cypress Dashboard "
        continue-on-error: true
        with:
          record: true
          spec: "*/*/*/cypressDashTest.spec.js"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
