name: " 🚀 smokeTest"
on:
  workflow_dispatch:
jobs:
  cypress-run:
    environment: trade-tariff
    env:
      CYPRESS_BASE_URL: "https://staging.trade-tariff.service.gov.uk"
      CYPRESS_SPACE: "STAGING"
      CYPRESS_STAGING_BASIC_AUTH: ${{ secrets.CYPRESS_STAGING_BASIC_AUTH }}
      CYPRESS_STAGING_BASIC_PASSWORD: ${{ secrets.CYPRESS_STAGING_BASIC_PASSWORD }}
      CYPRESS_STAGING_BASIC_USERNAME: ${{ secrets.CYPRESS_STAGING_BASIC_USERNAME }}

    name: "smoke tests - UK and XI"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - run: date
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        name: "UK and XI smoke tests"
        continue-on-error: true
        with:
          quiet: true
          browser: chrome
          headless: true
          spec: "cypress/e2e/HOTT-Shared/smokeTestCI.spec.js"
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./cypress/reports/mochawesome/
